services:
  - type: web
    name: chatgpt-proxy-rust
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CHATGPT_SESSION_TOKEN
        sync: false
      - key: PORT
        value: 3040
      - key: HOST
        value: 0.0.0.0
      - key: PROXY_API_KEY
        sync: false
      - key: ALLOWED_DIRECTORIES
        value: /tmp
      - key: ALLOWED_SHELL_COMMANDS
        value: ls,cat,grep,echo
    healthCheckPath: /health
    plan: starter
